((org-mode . ((fill-column . 76)
	      (org-description-max-indent . 5)
	      (org-src-preserve-indentation . 't)
	      (truncate-lines . nil)
	      (mode . iimage)
	      (ispell-local-dictionary . "british")
	      (mode . flyspell)
		;;(mode . longlines)
		;;(mode . reftex)
		))
 (latex-mode . ((fill-column . 76)
		;;(mode . flyspell)
		;;(mode . longlines)
		(mode . reftex)
		(mode . tex-pdf))))
